import { readingTimeMinutes } from '../../api/_lib/readingTime'
import type { LaunchPost } from './parsePost'

const BYLINE = 'Between the Bread'

const quote = (value: string): string => `'${value.replace(/'/g, "''")}'`

const textArray = (values: string[]): string => `ARRAY[${values.map(quote).join(', ')}]::text[]`

const dollarQuote = (body: string): string => {
  const tag = ['body', ...Array.from({ length: 50 }, (_value, index) => `body${String(index + 1)}`)].find(
    (candidate) => !body.includes(`$${candidate}$`),
  )
  if (tag === undefined) throw new Error('Could not find a safe quoting tag for a post body')
  return `$${tag}$${body}$${tag}$`
}

const postToSql = (post: LaunchPost): string =>
  [
    'WITH new_post AS (',
    '    INSERT INTO blog_posts (slug, title, excerpt, body, related_sandwich_slugs, author_name, meta_description, reading_time_minutes, published)',
    `    VALUES (${[
      quote(post.slug),
      quote(post.title),
      quote(post.excerpt),
      dollarQuote(post.body),
      textArray(post.related_sandwich_slugs),
      quote(BYLINE),
      quote(post.meta_description),
      String(readingTimeMinutes(post.body)),
      'false',
    ].join(', ')})`,
    '    ON CONFLICT (slug) DO NOTHING',
    '    RETURNING id',
    ')',
    'INSERT INTO blog_post_categories (post_id, category_id)',
    'SELECT n.id, c.id',
    'FROM new_post n',
    `CROSS JOIN blog_categories c WHERE c.slug IN (${post.category_slugs.map(quote).join(', ')});`,
  ].join('\n')

export const toSql = (posts: LaunchPost[], options: { source?: string }): string => {
  const header = [
    `-- Blog seed${options.source === undefined ? '' : `: ${options.source}`} (${String(posts.length)} posts)`,
    '-- Generated by scripts/generateBlogSeed.ts. Posts arrive as unpublished drafts; review, edit and publish them in the admin.',
    '-- Safe to run more than once. A post that already exists is left completely untouched, including its categories.',
  ]
  return [...header, '', ...posts.map(postToSql).flatMap((sql) => [sql, ''])].join('\n')
}
