import type { Chart, Cohort, CohortRule, Dashboard, Series } from './definitions'

const DISPLAY_WORDS = { line: 'a line chart', bar: 'a bar chart', table: 'a table' } as const

const ruleText = ({ event, atLeast, withinDays }: CohortRule): string =>
  atLeast > 1
    ? `\`${event}\` at least ${String(atLeast)} times in the last ${String(withinDays)} days`
    : `\`${event}\` in the last ${String(withinDays)} days`

const seriesText = ({ event, filters }: Series): string =>
  filters === undefined || filters.length === 0
    ? `\`${event}\``
    : `\`${event}\` where ${filters.map(({ key, value }) => `\`${key}\` = \`${String(value)}\``).join(' and ')}`

const cohortSection = (cohort: Cohort): string =>
  [
    `### ${cohort.name}`,
    '',
    cohort.description,
    '',
    'Create a dynamic cohort. Match people who meet **any** of these:',
    '',
    ...cohort.anyOf.map((group) => `- ${group.map(ruleText).join(' **and** ')}`),
    '',
  ].join('\n')

const chartSection = (chart: Chart): string => {
  if (chart.kind === 'funnel') {
    return [
      `### ${chart.name}`,
      '',
      chart.description,
      '',
      `Funnel insight, last ${String(chart.days)} days, steps completed within ${String(chart.windowDays)} day${chart.windowDays === 1 ? '' : 's'}.`,
      '',
      ...chart.steps.map((step, index) => `${String(index + 1)}. ${seriesText(step)}`),
      '',
    ].join('\n')
  }
  return [
    `### ${chart.name}`,
    '',
    chart.description,
    '',
    `Trends insight, shown as ${DISPLAY_WORDS[chart.display]}, last ${String(chart.days)} days.`,
    '',
    ...chart.series.map((series) => `- Event ${seriesText(series)}`),
    ...(chart.breakdown === undefined ? [] : ['', `Break down by event property \`${chart.breakdown}\`.`]),
    '',
  ].join('\n')
}

const dashboardSection = (dashboard: Dashboard): string =>
  [
    `## Dashboard: ${dashboard.name}`,
    '',
    dashboard.description,
    '',
    'Create the dashboard, then add each insight below to it.',
    '',
    ...dashboard.charts.map(chartSection),
  ].join('\n')

export const setupGuide = ({ cohorts, dashboards }: { cohorts: Cohort[]; dashboards: Dashboard[] }): string =>
  [
    '# PostHog setup guide',
    '',
    'Generated by `pnpm posthog:setup` from `scripts/posthog/definitions.ts`. Build these by hand in PostHog if the script cannot create them.',
    '',
    '## User groups (cohorts)',
    '',
    ...cohorts.map(cohortSection),
    ...dashboards.map(dashboardSection),
  ].join('\n')
