import type { EncyclopediaEntry } from './types'

const quote = (value: string): string => `'${value.replace(/'/g, "''")}'`

const nullable = (value: string | null): string => (value === null ? 'NULL' : quote(value))

const textArray = (values: string[]): string => `ARRAY[${values.map(quote).join(', ')}]::text[]`

const UPDATABLE_COLUMNS = [
  'name',
  'alternative_names',
  'description',
  'history',
  'origin_country',
  'origin_region',
  'canonical_ingredients',
  'dietary_tags',
] as const

const conflictClause = (update: boolean): string =>
  update
    ? `ON CONFLICT (slug) DO UPDATE SET\n    ${[...UPDATABLE_COLUMNS.map((column) => `${column} = EXCLUDED.${column}`), 'updated_at = now()'].join(',\n    ')};`
    : 'ON CONFLICT (slug) DO NOTHING;'

const entryToSql = (entry: EncyclopediaEntry, update: boolean): string =>
  [
    'INSERT INTO sandwich_database (name, slug, alternative_names, description, history, origin_country, origin_region, canonical_ingredients, dietary_tags, image_url, published)',
    `VALUES (${[
      quote(entry.name),
      quote(entry.slug),
      textArray(entry.alternative_names),
      quote(entry.description),
      quote(entry.history),
      nullable(entry.origin_country),
      nullable(entry.origin_region),
      `${quote(JSON.stringify(entry.canonical_ingredients))}::jsonb`,
      textArray(entry.dietary_tags),
      nullable(entry.image_url),
      String(entry.published),
    ].join(', ')})`,
    conflictClause(update),
  ].join('\n')

export const toSql = (entries: EncyclopediaEntry[], options: { update?: boolean; source?: string }): string => {
  const update = options.update === true
  const header = [
    `-- Encyclopedia import${options.source === undefined ? '' : `: ${options.source}`} (${String(entries.length)} entries)`,
    '-- Generated by scripts/importEncyclopedia.ts or scripts/seedEncyclopedia.ts. New imports arrive unpublished; review and publish them in the admin.',
    update
      ? '-- Safe to run more than once. Re-running refreshes the written content of existing entries and leaves everything else alone.'
      : '-- Safe to run more than once. Entries that already exist are left untouched.',
  ]
  return [...header, '', ...entries.map((entry) => entryToSql(entry, update)).flatMap((sql) => [sql, ''])].join('\n')
}
