-- Blog seed: launch posts (4 posts)
-- Generated by scripts/generateBlogSeed.ts. Posts arrive as unpublished drafts; review, edit and publish them in the admin.
-- Safe to run more than once. A post that already exists is left completely untouched, including its categories.

WITH new_post AS (
    INSERT INTO blog_posts (slug, title, excerpt, body, related_sandwich_slugs, author_name, meta_description, reading_time_minutes, published)
    VALUES ('best-cheese-for-grilled-cheese', 'The Best Cheeses for Grilled Cheese (and the Ones That Don''t Melt Well)', 'The best grilled cheese cheeses are young, moist and fairly fatty, like cheddar, American, Gruyère and fontina. Here is how to choose, which combinations work, and which cheeses stay stubbornly firm.', $body$The best cheese for grilled cheese has to do two jobs: it has to melt into a smooth, gooey layer, and it has to taste good when it is warm. Very few cheeses do both perfectly on their own, which is why so many cooks use a blend. Once you know why some cheeses melt and others refuse to, choosing gets easy.

## What makes a cheese melt

Four things matter most: moisture, fat, age and acidity.

- **Moisture and fat.** Younger, moister, fairly high-fat cheeses soften and flow readily.
- **Age.** As cheese ages it loses moisture and its protein network tightens. Instead of flowing, an old cheese tends to split into firm bits and grease.
- **Acidity and how it is made.** Some cheeses, such as halloumi and paneer, are made in a way that keeps them firm when heated. Very fresh, crumbly cheeses such as feta just soften.

## The best melting cheeses

- **Cheddar.** The classic. Mild to medium cheddar melts smoothly. Very sharp, long-aged cheddar has more flavor but can turn oily and grainy, so it is best blended with something milder.
- **American.** A processed cheese made with emulsifying salts, so it melts as smoothly and creamily as any cheese can. The flavor is mild, which makes it a good gooey base.
- **Monterey Jack and Colby.** Mild, buttery and quick to melt. Pepper jack is Monterey Jack with chilies, if you want some heat.
- **Gruyère.** Nutty and full of flavor, and it melts well. It is a favorite for French-style sandwiches.
- **Fontina.** Creamy, slightly earthy and very good at melting.
- **Havarti.** Soft and buttery, and it melts smoothly.
- **Provolone.** Mild to sharp, and it stretches nicely.
- **Low-moisture mozzarella.** Very stretchy, but quite mild, so pair it with something with more flavor. Fresh mozzarella releases water as it heats, so pat it dry or your bread may turn soggy.
- **Swiss and Emmental.** Nutty, slightly sweet and good melters, though they can turn stringy.
- **Muenster and young Gouda.** Mild and easy melters.

As our [grilled cheese entry](/sandwiches/grilled-cheese) notes, cheddar and American are the most common fillings, though provolone and Gouda are also used.

## Combinations that work

A blend lets one cheese bring the flavor and the other bring the melt.

- **Sharp cheddar and American:** the flavor of the first with the creaminess of the second.
- **Cheddar and Gruyère:** sharp and nutty together.
- **Provolone and sharp cheddar:** stretchy with a bit of bite.
- **Fontina with a little grated Parmesan:** the fontina melts, and Parmesan pressed into the buttered outside of the bread browns into a crisp, savory crust.
- **Monterey Jack and pepper jack:** easy melting with a gentle kick.

## Cheeses that don't melt well

These are not bad cheeses. They just do a different job.

- **Aged hard cheeses** such as Parmesan, Pecorino and aged Manchego soften and brown, but they do not turn gooey. Use them as a sprinkle for flavor and crunch, not as the main cheese.
- **Feta, queso fresco and cotija** crumble and soften instead of flowing.
- **Halloumi and paneer** hold their shape when heated. They are wonderful fried or grilled, but they will not give you a melty pull.
- **Fresh goat cheese, ricotta and cream cheese** warm up and turn creamy, but they do not stretch. They are fine as an addition for tang, not as the main cheese.
- **Blue cheese** softens but is intense, so a little goes a long way.
- **Bagged pre-shredded cheese** is often coated with a starch or cellulose powder so the shreds do not clump, which can make it melt a little less smoothly than cheese you shred yourself.

## Getting the most out of any cheese

- **Shred it.** Small pieces melt quickly and evenly.
- **Take the chill off.** Ten or fifteen minutes on the counter helps it melt before the bread browns.
- **Keep the heat low.** Even the best melting cheese will lose to a hot pan, so read our guide on [how to keep grilled cheese from burning before the cheese melts](/blog/keep-grilled-cheese-from-burning).

## Cheese in other classic sandwiches

The same qualities explain the cheeses in famous sandwiches. A classic [croque monsieur](/sandwiches/croque-monsieur) is typically made with Gruyère or a similar Alpine cheese. A [Reuben](/sandwiches/reuben) usually calls for Swiss, which melts well over corned beef and sauerkraut. And [mozzarella in carrozza](/sandwiches/mozzarella-in-carrozza), the Italian fried mozzarella sandwich, is built around exactly the stretchy melt that mozzarella is known for.

## If you need dairy-free

Plant-based cheeses melt on their own terms, and they vary a lot between brands. Our [vegan grilled cheese guide](/blog/vegan-grilled-cheese) explains what to look for on the label and how to cook them.

Cheese chosen, sandwich cooked? Next, decide [what to serve with grilled cheese](/blog/what-to-serve-with-grilled-cheese).$body$, ARRAY['grilled-cheese', 'croque-monsieur', 'mozzarella-in-carrozza', 'reuben']::text[], 'Between the Bread', 'Best cheese for grilled cheese: cheddar, American, Gruyère, fontina and more. Plus the cheeses that won''t melt, and how to combine them for flavor.', 5, false)
    ON CONFLICT (slug) DO NOTHING
    RETURNING id
)
INSERT INTO blog_post_categories (post_id, category_id)
SELECT n.id, c.id
FROM new_post n
CROSS JOIN blog_categories c WHERE c.slug IN ('best-pairings');

WITH new_post AS (
    INSERT INTO blog_posts (slug, title, excerpt, body, related_sandwich_slugs, author_name, meta_description, reading_time_minutes, published)
    VALUES ('keep-grilled-cheese-from-burning', 'How to Keep Grilled Cheese From Burning Before the Cheese Melts', 'Burnt bread with cold, unmelted cheese inside almost always means the pan is too hot. Here is how to fix the heat, the cheese and the timing so the crust turns golden just as the middle turns gooey.', $body$You flip the sandwich and the bread is nearly black, but when you pull the halves apart the cheese is still stiff and cold. If your grilled cheese comes out burnt on the outside with the cheese not melted, you are not alone. It is one of the most common grilled cheese problems, and it has a simple cause: the bread is cooking much faster than the cheese is melting.

The fix is to slow the bread down and speed the cheese up. This guide covers both, in the order that makes the biggest difference.

## The short version

- Use medium-low heat, not medium-high.
- Cover the pan for a minute or two so trapped heat and steam melt the cheese.
- Use shredded or thinly sliced cheese, taken out of the fridge a few minutes early.
- Do not overfill. A thick pile of cheese needs more time than the bread can give it.
- Spread butter or mayonnaise thinly and evenly, right out to the edges.

## Why the outside burns first

Bread is thin and dry. Wherever it touches a hot pan, its surface browns within a couple of minutes and burns a few minutes after that. The cheese sits in the middle, insulated by two slices of bread, and it has to be warmed all the way through before it softens.

If the pan is hot enough to brown the bread in two minutes, the cheese has only had two minutes to warm up, which is rarely enough. Lowering the heat stretches out the time the bread takes to brown, and that gives the warmth time to reach the middle.

## Turn the heat down

Medium-low is the right place to start for most pans. Preheat for a minute or two, then reduce the heat and let the pan settle before the sandwich goes in. A good sign is butter that melts and foams gently without browning right away.

Plan on roughly three to five minutes per side. If that feels slow, it is working. A grilled cheese that takes its time is far more likely to finish with golden bread and cheese that stretches.

Your pan matters too. Cast iron and other heavy pans store a lot of heat, so they often need a lower setting than a thin nonstick pan. If the bread keeps scorching in a heavy pan, try a lower setting before you change anything else.

## Cover the pan

This is the most useful single trick. After the first flip, put a lid on the pan, or turn a baking sheet over a griddle, for one to two minutes. The trapped warm air and steam heat the top of the sandwich and soften the cheese without adding any more browning to the bread.

Lift the lid to check, and take it off for the last thirty seconds or so to re-crisp the crust.

## Help the cheese melt faster

- **Shred it.** Small pieces have more surface area and melt much sooner than a thick slice. Freshly shredded cheese also tends to melt more smoothly than bagged shreds, which are often coated with a starch or cellulose powder to keep them from sticking together.
- **Take the chill off.** Ten or fifteen minutes on the counter before cooking helps.
- **Spread it almost to the edges.** Cheese that only sits in the center leaves dry corners and an overloaded middle.
- **Choose a good melter.** Some cheeses resist melting however carefully you cook. Our guide to [the best cheeses for grilled cheese](/blog/best-cheese-for-grilled-cheese) explains which ones melt well and which do not.

## Pick the right fat and the right bread

Butter browns beautifully, but its milk solids darken quickly, so it is less forgiving on a hot pan. Mayonnaise, which is mostly oil and egg, spreads very thin and browns evenly, which is why many cooks swear by it. Either works if the heat is low. As the [grilled cheese entry](/sandwiches/grilled-cheese) in our encyclopedia notes, the outside of the bread is usually spread with butter or mayonnaise.

For the bread itself, slices about half an inch thick work well. Very thin slices toast before anything has time to melt, and very thick ones take so long to heat through that the surface darkens. Breads with added sugar or milk brown faster than plain ones, so give them a little extra attention.

## Rescue a sandwich that is already dark

If the bread is browned but the cheese is still stiff, you do not have to start over:

1. Turn the heat to low and cover the pan for a minute or two.
2. Or move the sandwich to a baking sheet in a 325°F (160°C) oven for a few minutes, until the cheese gives when you press gently on the top.
3. Skip the microwave. It will melt the cheese but leave the bread soft and chewy.

## Other melts need the same patience

Any sandwich that has to melt cheese inside or on top follows the same rule: the heat has to reach the cheese before the surface burns. A [croque monsieur](/sandwiches/croque-monsieur) is often finished in the oven so the cheese on top can melt and color gently. A [patty melt](/sandwiches/patty-melt), griddled with cheese over a beef patty and onions, does better with the same lid-and-low-heat approach.

## Quick troubleshooting

- **Bread burns, cheese is cold:** the heat is too high. Lower it and cover the pan.
- **Cheese melts, but the bread is pale:** raise the heat slightly for the last minute, or take the lid off to crisp the crust.
- **Cheese leaks out and burns in the pan:** the sandwich is overfilled. Use a little less cheese and keep it just inside the edges.
- **Making it dairy-free:** vegan cheese behaves differently, so read our [vegan grilled cheese guide](/blog/vegan-grilled-cheese).

Once the sandwich is right, the plate deserves the same care. Here is [what to serve with grilled cheese](/blog/what-to-serve-with-grilled-cheese) when you want something other than tomato soup.$body$, ARRAY['grilled-cheese', 'croque-monsieur', 'patty-melt']::text[], 'Between the Bread', 'Grilled cheese burnt on the outside but the cheese isn''t melted? Lower the heat, cover the pan and shred your cheese. Here''s how to get golden bread and fully melted cheese.', 5, false)
    ON CONFLICT (slug) DO NOTHING
    RETURNING id
)
INSERT INTO blog_post_categories (post_id, category_id)
SELECT n.id, c.id
FROM new_post n
CROSS JOIN blog_categories c WHERE c.slug IN ('techniques-and-guides');

WITH new_post AS (
    INSERT INTO blog_posts (slug, title, excerpt, body, related_sandwich_slugs, author_name, meta_description, reading_time_minutes, published)
    VALUES ('vegan-grilled-cheese', 'Vegan Grilled Cheese: Which Dairy-Free Cheeses Actually Melt', 'Dairy-free cheese melts very differently from dairy cheese, and brands vary widely. Learn which ingredients to look for, how to melt them without scorching the bread, and what else to check for a truly vegan sandwich.', $body$A vegan grilled cheese can be wonderful, or it can be a sandwich with a slab of warm, rubbery plastic inside. The difference is usually the cheese, and it is not always obvious from the package. Plant-based cheese is not one product. Brands and formulas vary a great deal, and recipes change over time, so no single brand wins every time.

What you can do is learn to read the label, choose the right type for the job, and cook it in a way that gives dairy-free cheese the best chance of melting. This guide shows you how. Whichever product you pick, try a small amount before you build a whole sandwich around it.

## Why dairy-free cheese melts differently

Dairy cheese melts because its milk proteins and fat soften together as they warm up. Plant-based cheeses have to imitate that with other ingredients, usually plant oils, starches and sometimes nuts or proteins. How well a vegan cheese melts depends almost entirely on its recipe.

## Read the label: what to look for

- **Coconut oil and starch.** Many supermarket slices and shreds are built from plant oil plus a starch such as tapioca, potato or corn. The starch tends to give some stretch and the oil softens as it warms, so these are often the most melty. They can stay firm if underheated, and turn greasy if overheated.
- **Nut-based.** Cashew and almond cheeses are often creamy and full of flavor. They tend to soften and spread rather than stretch, which makes them good for taste but less good for a long cheesy pull. They also contain tree nuts, which matters if anyone is allergic.
- **Other bases.** Soy, pea protein and other plant bases exist too, and their behavior varies widely. If the pack says the cheese melts, treat that as the maker's claim and check it with a small test.
- **Shreds, slices or blocks.** Shreds melt fastest. Blocks are slowest unless you grate or thinly slice them yourself.

## How to get dairy-free cheese to melt

1. **Shred it or slice it thin.** Small pieces warm through faster than a thick slab.
2. **Use medium-low heat and a lid.** Covering the pan traps steam and gentle heat. A few drops of water in the pan beside the sandwich, not on the bread, then a lid, creates steam that helps the cheese soften.
3. **Give it extra time.** Vegan cheeses often need longer than dairy cheese. Patience on low heat is better than turning it up, which can leave the bread burnt and the cheese cold. Our guide to [keeping grilled cheese from burning before the cheese melts](/blog/keep-grilled-cheese-from-burning) covers the heat in detail.
4. **Use two cheeses.** Pair one that melts and stretches with one that brings flavor, just as you would with dairy cheese. Our guide to [the best cheeses for grilled cheese](/blog/best-cheese-for-grilled-cheese) explains the idea.
5. **Add flavor.** Nutritional yeast is a popular way to add a savory, cheesy taste. A thin smear of mustard, a few caramelized onions or a splash of hot sauce also help a mild vegan cheese taste more like the real thing.
6. **Try a sauce.** A thin layer of a dairy-free cheese sauce, or a white sauce made with plant milk, between the slices can make the middle creamier.

## Check the rest of the sandwich

A sandwich is only vegan if everything in it is.

- **Bread.** Many sandwich breads contain milk, butter, honey or egg. Check the ingredients, because they differ from loaf to loaf.
- **Fat.** Use a vegan butter, olive oil or a vegan mayonnaise for the outside, and read the label to be sure.
- **Labels in general.** "Dairy-free" and "vegan" are not the same thing, since vegan also excludes things like honey and egg. Always read labels for allergens too, including nuts, soy and wheat. Ingredients change, and this guide cannot replace the label in your hand.
- **Gluten-free bread as well?** It tends to brown and dry out differently from regular bread, but the same low heat and covered pan help.

## Common problems

- **The cheese is greasy or oily:** the heat is too high. Turn it down.
- **The cheese stays firm or rubbery:** it needs more time covered on low heat, or it needs to be shredded finer.
- **It tastes flat:** add nutritional yeast, mustard or caramelized onions.
- **The bread burns first:** that is a heat problem, not a cheese problem. See the guide linked above.

## Toppings and what to serve

Vegan grilled cheese loves toppings that add moisture and flavor: sliced tomato, spinach, avocado, caramelized onions or roasted peppers. For the side, see [what to serve with grilled cheese](/blog/what-to-serve-with-grilled-cheese), and check the label on any soup, because some contain cream or butter.

## Take it further

The classic [grilled cheese](/sandwiches/grilled-cheese) is where to start. Other cheese-forward sandwiches in our encyclopedia, such as the [croque monsieur](/sandwiches/croque-monsieur) and [mozzarella in carrozza](/sandwiches/mozzarella-in-carrozza), are traditionally made with dairy and with ham or egg. Treat them as inspiration for a dairy-free adaptation rather than a direct swap.$body$, ARRAY['grilled-cheese', 'croque-monsieur', 'mozzarella-in-carrozza']::text[], 'Between the Bread', 'Vegan grilled cheese: learn which dairy-free cheeses melt best, what to look for on the label, and how to cook them so the bread browns without scorching.', 5, false)
    ON CONFLICT (slug) DO NOTHING
    RETURNING id
)
INSERT INTO blog_post_categories (post_id, category_id)
SELECT n.id, c.id
FROM new_post n
CROSS JOIN blog_categories c WHERE c.slug IN ('dietary');

WITH new_post AS (
    INSERT INTO blog_posts (slug, title, excerpt, body, related_sandwich_slugs, author_name, meta_description, reading_time_minutes, published)
    VALUES ('what-to-serve-with-grilled-cheese', 'What to Serve With Grilled Cheese (Beyond Tomato Soup)', 'Grilled cheese is rich and salty, so the best sides add acid, crunch or freshness. Here are soups, salads, pickles, fruit and drinks that go beyond tomato soup, plus easy ways to turn it into a meal.', $body$Tomato soup is the classic partner for grilled cheese for a good reason. It is warm and comforting, and its acidity cuts through the richness of the cheese and butter. The same idea works for far more than soup. Once you know why the pairing works, you can build a plate that never gets boring.

## The rule: balance the richness

A grilled cheese is rich, salty and soft. The best sides push back with at least one of these:

- **Acid:** tomatoes, vinegar, pickles, citrus.
- **Crunch:** crisp vegetables, chips, fries.
- **Freshness:** raw greens, herbs, cold salads.
- **A little sweetness:** fruit, roasted vegetables, a sweet-tart dip.

Pick one or two, and the sandwich tastes better for it.

## Soups beyond tomato

- **Roasted red pepper.** Sweet and slightly tangy, so it behaves much like tomato soup.
- **Butternut squash.** Creamy and sweet. It goes especially well with a sharp cheddar sandwich.
- **Chicken noodle.** Pure comfort, and it makes the plate a full meal.
- **Minestrone or vegetable soup.** Light, fresh and full of vegetables.
- **Lentil soup.** Earthy and filling.
- **Gazpacho.** A cold, tangy option for a hot day.

## Salads and slaws

A crisp, sharply dressed salad is the easiest way to balance a grilled cheese.

- A simple green salad with a lemon or vinegar dressing.
- Arugula with lemon and a little olive oil.
- A crunchy cabbage slaw.
- Cucumber salad.

## Pickles and other sharp things

Anything pickled does the same job as the acid in tomato soup.

- Dill pickles and cornichons.
- Pickled red onions.
- Giardiniera or banana peppers.
- Hot sauce or whole-grain mustard for dipping.

## Fruit

Apple and cheddar are an old favorite, so apple slices on the side make sense. Pear slices and grapes work for the same reason: they are sweet, juicy and a little tart. Some people add a thin spread of jam or chutney inside the sandwich for the same effect.

## Something crunchy

- Kettle-style potato chips.
- Oven fries or roasted potatoes.
- Roasted vegetables such as broccoli or Brussels sprouts.
- Crispy roasted chickpeas.

## Dips and extras

Ketchup is perfectly fine. If you want something different, try mustard, pesto, chutney or a drizzle of hot honey.

## Drinks

Crisp, cold drinks do well with rich food: iced tea with lemon, lemonade, or sparkling water with citrus. If you are pouring something alcoholic, a crisp lager, a dry cider or a dry white wine is a classic match.

## Three easy plates

- **Quick lunch:** grilled cheese, dill pickles and apple slices.
- **Cozy dinner:** grilled cheese, roasted red pepper soup and a simple green salad.
- **Summer meal:** grilled cheese, cucumber salad and iced tea, or a small bowl of gazpacho.

## Make the sandwich the star

A great side cannot rescue a poorly made sandwich, so it is worth getting the main event right:

- Choose a cheese that melts well, using our guide to [the best cheeses for grilled cheese](/blog/best-cheese-for-grilled-cheese).
- Keep the heat under control so the bread browns evenly, with the tips in [how to keep grilled cheese from burning before the cheese melts](/blog/keep-grilled-cheese-from-burning).
- Cooking for someone dairy-free? Our [vegan grilled cheese guide](/blog/vegan-grilled-cheese) shows how to choose and cook plant-based cheese, and it is worth checking labels on any soup too.

If you want something heartier than a plain [grilled cheese](/sandwiches/grilled-cheese), a [tuna melt](/sandwiches/tuna-melt) or a [patty melt](/sandwiches/patty-melt) are both cheese sandwiches with more going on inside. And if you are not sure what to make at all, [roll a random sandwich in the generator](/).$body$, ARRAY['grilled-cheese', 'tuna-melt', 'patty-melt']::text[], 'Between the Bread', 'What to serve with grilled cheese besides tomato soup: other soups, salads, pickles, fruit, dips and drinks, plus easy combinations for lunch or dinner.', 4, false)
    ON CONFLICT (slug) DO NOTHING
    RETURNING id
)
INSERT INTO blog_post_categories (post_id, category_id)
SELECT n.id, c.id
FROM new_post n
CROSS JOIN blog_categories c WHERE c.slug IN ('sandwich-ideas');
